### ISSUE TITLE
Expanding TEs

### ISSUE THREAD

**Issue by sjg20** [FirmwareHandoff/firmware_handoff#23]
This came up in Julius' review of the U-Boot updates (v1).

https://patchwork.ozlabs.org/project/uboot/patch/20230725213634.255345-15-sjg@chromium.org/

* The bloblist_resize() function doesn't preserve alignment
restrictions when relocating other TEs. I think the (only?) safe way
to resize a TE in-place would be to align the distance that following
TEs need to be moved up to (1 << hdr->align_log2), and then insert a
void dummy TE to account for the additional added distance if
necessary.

I am not sure how to expand a TE and push up the ones above it:

1. We dropped the hdr_size thing which was providing per-TE alignment. We did talk about having an alignment field in the TE but that was dropped in favour of using VOID TEs
2. We also dropped the requirement that the bloblist itself must start on the max alignment that will be needed by any TE. Instead we have an 'alignment_offset' which seems clever, but perhaps is an over-complication? It seems to me that (when an entry needs to be added with larger alignment) relocating a TL to an address which fits the alignment is easier. It is also likely only to be needed later in boot, where there is plenty of memory.

In fact I am actually not sure how to expand an entry, while preserving the alignment of entries above it.

Consider:
bloblist starting at 0
TE0 at 0x20 (i.e. hdr starts at 0x18), alignment = 4, size=8
TE1V at 0x30 (i.e. hdr starts at 0x28), size=0x10 (void entry for TE1)
TE1 at 0x40 (i.e. hdr starts at 0x38), alignment = 5, size=0x10

Let's say we want to expand TE0 such that it can hold 0x20 bytes. What should we do?

Overall I worry that this has got a bit too complicated.

**Comment by jwerner-chromium** [comment]
I think the method I suggested on that email thread works fine and we should add it to the "standard operations" section if we think there's a common need for this? It's not a super complicated algorithm, Raymond has an implementation for it in his TF-A code here: https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/22215/22/lib/transfer_list/transfer_list.c#268

Resizing existing TEs is a "bad" operation because it requires memoving the entire rest of the list every time, which is very inefficient. So I originally didn't write that up in the "standard operations" because I was hoping people would just not want to do that at all. But if there is demand for this operation, this is how you'd do it.

**Comment by sjg20** [comment]
I added an issue to U-Boot

https://source.denx.de/u-boot/u-boot/-/issues/43
